### ISSUE TITLE
Please always check the error cores of mlock/munlock

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#12]
I see that ```mlock``` fails, but you don't check for errors.

**Comment by ventosus** [comment]
Why should I? e.g. what action could I take if I knew it failed?

App needs to run nevertheless, even if mlock fails. This just adds unnecessary code.

Instead I've removed some unnecessary mlocks (https://github.com/OpenMusicKontrollers/synthpod/commit/f8edb245bd03234102c61ed8dd67a0d2a7cf8e72), because I mlockall at app start already.

**Comment by yurivict** [comment]
The can fail for any reason, ex. bug in your app, bug in the platform.

> what action could I take if I knew it failed?

At least print a warning. Otherwise you may as well remove them, because it's ok when they fail too.
