### ISSUE TITLE
Midi bindings

### ISSUE THREAD

**Issue by cmt227** [OpenMusicKontrollers/synthpod#2]
Hi,

This is not necessarily a software bug. My idea use case for Synthpod is as an LV2 host for live performance. I would love to be able to create MIDI "bindings" from my keyboard controller to any control ports on a plugin, that can be saved and reopened later. Does Synthpod allow me to do that? If so, what is the process to create these bindings? Thanks!

-Carsten

**Comment by ventosus** [comment]
> My idea use case for Synthpod is as an LV2 host for live performance

That's my use case, too

>  I would love to be able to create MIDI "bindings" from my keyboard controller to any control ports on a plugin, that can be saved and reopened later. Does Synthpod allow me to do that? If so, what is the process to create these bindings?

Synthpod can do that. It works differently than you may be accustomed from other plugin hosts, though. You can change pretty much any plugin parameter by scripting/interacting with Synthpod's API, but the latter is neither documented nor stable (in terms of its namespace), so that's no option right now.

The Synthpod plugin engine has no idea what MIDI is in the first place, it therefore does not analyse it. Its responsibility is 'running plugins' and 'routing audio, CV, event and control signals'. With it's modular approach, everything else shall be implemented by plugins.

In f4f4b04, I have prototyped a new plugin (synthpod#midi2control) which should do what you want.
It features 8 control slots, enabled with MIDI learn and automatic range detection

- spawn as many of the plugin as you need
- connect the synthpod#midi2control event input to your MIDI controller source
- connect the synthpod#midi2control control outputs to any other plugins control inputs

P.s. in order to be able to connect control ports, you need to toggle their visibility (chain link icon) to make them show up in the matrix patch bay
