### ISSUE TITLE
Jack ports randomly disappear

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/synthpod#20]
I'm running synthpod_nk and using Catia to route in/out to system with JACK.

After a few minutes of operation, the Synthpod jack client disappears and Synthpod no longer recieves audio input (or provides audio output).

Looksl like the JACK client randomly dies, but the GUI carries on.

Anybody else having similar problems?

**Comment by ventosus** [comment]
If you have synthpod_nk, you're not up-to-date, it is called synthpod_ui since a while :)

The UI runs in its own process, if the DSP side dies, it may indeed carry on. Keep-alive messages are on the todo list.

If synthpod jack client disappeared, then it may indeed have crashed (because of itself or a faulty plugin). Congratulations, you've found a bug.

There are different ways of starting synthpod and its UI:

You can start them both in one command:

    synthpod_jack -g

Or separately:

    synthpod_jack -G
    synthpod_ui

If started in one command, closing the UI, will automatically close the jack client, too. Not so with when started as daemon

**Comment by ventosus** [comment]
A gdb backtrace (of the latest version) would help, of coarse
