### ISSUE TITLE
[question] Why do you need to create separate executables for each UI type?

### ISSUE THREAD

**Issue by yurivict** [OpenMusicKontrollers/synthpod#9]
synthpod_sandbox_x11/synthpod_sandbox_gtk3/synthpod_sandbox_qt5

You can run any UI from one executable, even at the same time if needed.

Having separate executables only adds complexity to the build process, and adds another unnecessary choice to make for users.

**Comment by ventosus** [comment]
> You can run any UI from one executable, even at the same time if needed.

No, you cannot (and should not) link an executable at the same time to Gtk2+Gtk3 or Qt4+Qt5. And using those big toolkits for plugin UIs is ill-advised in the first place, so they are optional (and disabled by default).

http://lists.lv2plug.in/pipermail/devel-lv2plug.in/2016-March/001593.html

I have a strict rule for synthpod development: Everything that can be run in a separate process, should do so. I want to use it for live performances, it must not crash just because of any exotic UI lib clashes.

**Comment by yurivict** [comment]
Ok, thanks!
